# use an existing image as base 
FROM node:16-alpine

WORKDIR /app

# copy package.json
COPY ./package.json ./ 

# Download and install 
RUN npm install
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

# copy all
COPY ./ ./ 

# Command  
CMD [ "npm", "run","start" ]